version: "3.9"

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

  php:
    image: php:8.2-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    working_dir: /var/www/html
    networks:
      - wp-network
    depends_on:
      - db
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y wget unzip libpng-dev libjpeg-dev libfreetype6-dev libzip-dev &&
      docker-php-ext-install mysqli gd zip &&
      wget https://wordpress.org/latest.zip -O /tmp/wordpress.zip &&
      unzip /tmp/wordpress.zip -d /tmp &&
      cp -r /tmp/wordpress/* /var/www/html &&
      chown -R www-data:www-data /var/www/html &&
      php-fpm
      "

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
    driver: bridge
